[workspace]
members = [
    "cfg", 
    "statement_cov",
    "branch_cov",
    "cyclomatic_complexity",
    ".",     
]


[package]
name = "skan-uj-kod"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
walkdir = "2.3"
tempfile = "3.3"
go-parser = "0.1"
cfg = { path = "./cfg" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
statement_cov = { path = "./statement_cov" }
cyclomatic_complexity = { path = "./cyclomatic_complexity" }
branch_cov = { path = "./branch_cov" }
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
indicatif = "0.17"
toml = "0.8"
dashmap = "5.5"
rayon = "1.8"
