[workspace]
members = [
    "cfg", 
    "statement_cov",
    ".",     
]


[package]
name = "skan-uj-kod"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
walkdir = "2.3"
tempfile = "3.3"
go-parser = "0.1"
cfg = { path = "./cfg" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
statement_cov = { path = "./statement_cov" }
