[package]
name = "skan-uj-kod"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ 
    "crates/go-parser",
    "crates/go-types", 
    "crates/kernel", 
    "crates/plugin_interface",
    "crates/plugins/plugin1"]
